=== adrib2727/Repositorio2DAWADRIB27/Asignaturas/LenguajeMarcas/EjerciciosMarcas/xml/TareasAnteriores/archivo3.dtd
<!ELEMENT Ticket (fecha, hora, precio, forma_pago, datos_comercio, datos_compra)>
<!ATTLIST Ticket id_ticket ID #REQUIRED>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT hora (#PCDATA)>
    <!ELEMENT precio (precioNoIva, iva, precioTotal)>
    <!ATTLIST precio moneda ID #REQUIRED>
        <!ELEMENT precioNoIva (#PCDATA)>
        <!ELEMENT iva (#PCDATA)>
        <!ELEMENT precioTotal (#PCDATA)>
    <!ELEMENT forma_pago (tarjeta)>
    <!ELEMENT tarjeta (nombre_cliente, digitos_tarjeta)>
        <!ELEMENT nombre_cliente (#PCDATA)>
        <!ELEMENT digitos_tarjeta (#PCDATA)>
    <!ELEMENT datos_comercio (nombre, direccion, cif, telefono)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT cif (#PCDATA)>
        <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT datos_compra (nombre_articulo, cantidad, precio_sin_iva, porc_IVA, pvp)>
        <!ELEMENT nombre_articulo (#PCDATA)>
        <!ELEMENT cantidad (#PCDATA)>
        <!ELEMENT precio_sin_iva (#PCDATA)>
        <!ELEMENT porc_IVA (#PCDATA)>
        <!ELEMENT pvp (#PCDATA)>

=== adrib2727/Repositorio2DAWADRIB27/Asignaturas/LenguajeMarcas/EjerciciosMarcas/xml/TareasAnteriores/archivo3.xml
<?xml version="1.0"?>
<!DOCTYPE Ticket SYSTEM "archivo3.dtd">
<Ticket id_ticket="A01">
    <fecha>Miercoles 23 de Septiembre</fecha>
    <hora>17:30</hora>
    <precio moneda="euro">
        <precioNoIva>56.87</precioNoIva>
        <iva>11.94</iva>
        <precioTotal>68.81</precioTotal>
    </precio>
    <forma_pago>
        <tarjeta>
            <nombre_cliente>Adrián Ibáñez Soriano</nombre_cliente>
            <digitos_tarjeta>12</digitos_tarjeta>
        </tarjeta>
    </forma_pago>
    <datos_comercio>
        <nombre>American Jewerly</nombre>
        <direccion>Detroit</direccion>
        <cif>546873432-D</cif>
        <telefono>648433153</telefono>
    </datos_comercio>
    <datos_compra>
        <nombre_articulo>Aspiradora Industrial</nombre_articulo>
        <cantidad>2</cantidad>
        <precio_sin_iva>56.87</precio_sin_iva>
        <porc_IVA>11.94</porc_IVA>
        <pvp>68.81</pvp>
    </datos_compra>
</Ticket>
