=== adrib2727/Repositorio2DAWADRIB27/Asignaturas/LenguajeMarcas/EjerciciosMarcas/xml/TareasAnteriores/archivo2.dtd
<!ELEMENT Taller (mecanico, coche_reparado, propietario, trabajo)>
<!ATTLIST Taller codigo ID #REQUIRED>
    <!ELEMENT mecanico (nombre1)>
        <!ELEMENT nombre1 (#PCDATA)>
    <!ELEMENT coche_reparado (matricula, marca, modelo)>    
        <!ELEMENT matricula (#PCDATA)>
        <!ELEMENT marca (#PCDATA)>
        <!ELEMENT modelo (#PCDATA)>
    <!ELEMENT propietario (nombre2, apellidos)>
        <!ELEMENT nombre2 (#PCDATA)>  
        <!ELEMENT apellidos (#PCDATA)>  
    <!ELEMENT trabajo (fecha_inicio, fecha_fin, valor, informe)>
        <!ELEMENT fecha_inicio (#PCDATA)>
        <!ELEMENT fecha_fin (#PCDATA)>
        <!ELEMENT valor (#PCDATA)>
        <!ELEMENT informe (#PCDATA)>

=== adrib2727/Repositorio2DAWADRIB27/Asignaturas/LenguajeMarcas/EjerciciosMarcas/xml/TareasAnteriores/archivo2.xml
<?xml version="1.0"?>
<!DOCTYPE Taller SYSTEM "archivo2.dtd">
<Taller codigo="A135">
    <mecanico>
        <nombre1>Josue Vergara</nombre1>
    </mecanico>
    <coche_reparado>
        <matricula>23847DASS</matricula>
        <marca>Lamborghini</marca>
        <modelo>Aventador</modelo>
    </coche_reparado>
    <propietario>
        <nombre2>Pepe</nombre2>
        <apellidos>Rodríguez</apellidos>
    </propietario>
    <trabajo>
        <fecha_inicio>30/11/20</fecha_inicio>
        <fecha_fin>02/12/20</fecha_fin>
        <valor>Valor en €</valor>
        <informe>Cambio de neumáticos </informe>
    </trabajo>
</Taller>
